right_hand_traj_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - r_rh_p12_rn

  constraints:
    goal_time: 2.0
    stopped_velocity_tolerance: 1.0
    r_rh_p12_rn:
      goal: 0.5
      trajectory: 1.0
